name: orogprecip
channels:
 - conda-forge
dependencies:
 - python=3.9.16
 - numpy=1.24.2
 - scipy=1.10.1
 - xarray=2023.4.1
 - pandas=2.0.0 
 - cartopy=0.21.1
 - matplotlib=3.7.1
 - scikit-learn=1.2.0
 - netcdf4=1.6.4
 - zarr=2.16.1
 - jupyter
